app1/urls.py
from django.urls import path
from app1.views import *
app_name='vasu'

urlpatterns=[
    path('app1_first/',app1_first,name='app1_first'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='deva'

urlpatterns=[
    path('app2_second/',app2_second,name='app2_second'),
]

project18/urls.py
from django.contrib import admin
from django.urls import path,include
import app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def app1_first(request):
    return render(request,'app1_first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2_second(request):
    return render(request,'app2_second.html')

templates/app1_first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h3>this my urlhtml page </h3>
        <a href="{% url 'deva:app2_second' %}">mapping second url </a>
    </center>
    
</body>
</html>

templates/app2_second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
        <h1> this app2 urls html page</h1>
        <a href="{% url 'vasu:app1_first' %}">mapping first url </a>
     
    
</body>
</html>